"""
Symmetric encryption for storage provider credentials.

Why: provider docs in Pocketbase hold raw access_key + secret_access_key
(and SFTP passwords). Even with restrictive PB rules, leaving them as
plaintext means an admin-token leak = total credential disclosure.
Encrypting at rest with a server-only env-var key means a stolen DB
backup alone is not enough.

Algorithm: AES-256-GCM. 12-byte random nonce per ciphertext, prepended
to the ciphertext + auth tag and base64-encoded for storage. Standard
and well-supported on every Python that ships `cryptography`.

Format on disk:
    "v1:<base64(nonce || ciphertext || tag)>"

The "v1:" prefix lets us evolve the format later (rotate key, switch
algorithm) without ambiguity for old records.

Key source: env var STORAGE_PROVIDERS_ENC_KEY — must be 32 hex bytes
(generated by `openssl rand -hex 32`). The compose stack passes it to
both dashboard and any backend that touches provider secrets.
"""
from __future__ import annotations

import base64
import logging
import os
import secrets
from typing import Optional

log = logging.getLogger(__name__)

_KEY_ENV = "STORAGE_PROVIDERS_ENC_KEY"


def _key_bytes() -> Optional[bytes]:
    """Resolve the encryption key from env. Returns None when missing
    so callers can degrade to "stored as plaintext" mode during local
    dev (with a loud warning)."""
    raw = (os.getenv(_KEY_ENV) or "").strip()
    if not raw:
        return None
    try:
        # Accept either hex (preferred) or base64 — easier on humans.
        if all(c in "0123456789abcdefABCDEF" for c in raw):
            kb = bytes.fromhex(raw)
        else:
            kb = base64.b64decode(raw)
    except Exception as e:
        log.error(f"{_KEY_ENV} is set but not parseable: {e}")
        return None
    if len(kb) != 32:
        log.error(f"{_KEY_ENV} must be 32 bytes (got {len(kb)}); using plaintext fallback")
        return None
    return kb


def encrypt(plaintext: str) -> str:
    """Encrypt `plaintext` for storage. Returns the v1: tagged string
    (or, if no key configured, falls back to base64-with-warning so
    local dev keeps working)."""
    if plaintext is None or plaintext == "":
        return ""
    key = _key_bytes()
    if key is None:
        log.warning(
            "%s not configured — storing provider secret as base64 only "
            "(NOT secure; set this env var in production)", _KEY_ENV,
        )
        return "b64:" + base64.b64encode(plaintext.encode("utf-8")).decode("ascii")

    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    nonce = secrets.token_bytes(12)
    ct = AESGCM(key).encrypt(nonce, plaintext.encode("utf-8"), associated_data=None)
    return "v1:" + base64.b64encode(nonce + ct).decode("ascii")


def decrypt(ciphertext: str) -> str:
    """Decrypt a stored secret. Handles both v1: AES-GCM and the b64:
    fallback. Returns the original plaintext."""
    if not ciphertext:
        return ""
    if ciphertext.startswith("b64:"):
        return base64.b64decode(ciphertext[4:]).decode("utf-8")
    if not ciphertext.startswith("v1:"):
        # Legacy unprefixed value — assume plaintext (covers a brief
        # window before encryption was introduced).
        return ciphertext

    key = _key_bytes()
    if key is None:
        raise RuntimeError(
            f"Encrypted provider secret found but {_KEY_ENV} is not set"
        )
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    blob = base64.b64decode(ciphertext[3:])
    nonce, ct = blob[:12], blob[12:]
    return AESGCM(key).decrypt(nonce, ct, associated_data=None).decode("utf-8")


def mask(secret: str, *, keep: int = 4) -> str:
    """For UI display — show only the last `keep` chars."""
    if not secret:
        return ""
    if len(secret) <= keep:
        return "*" * len(secret)
    return "*" * (len(secret) - keep) + secret[-keep:]
